// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ToolkitstylesModuleScssNamespace {
  export interface IToolkitstylesModuleScss {
    dropzone: string;
    dropzone__acceptedFormats: string;
    dropzone__deleteButton: string;
    dropzone__errormessage: string;
    dropzone__files: string;
    dropzone__files__file: string;
    dropzone__loader: string;
    dropzone__uploadButton: string;
    'dropzone__visual-dropzone': string;
    'dropzone__visual-dropzone--dragover': string;
    'dropzone__visual-dropzone--visible': string;
    'dropzone__visual-dropzone__button': string;
    'dropzone__visual-dropzone__button--visible': string;
    'dropzone__visual-dropzone__label': string;
    'dropzone__visual-dropzone__label--visible': string;
  }
}

declare const ToolkitstylesModuleScssModule: ToolkitstylesModuleScssNamespace.IToolkitstylesModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ToolkitstylesModuleScssNamespace.IToolkitstylesModuleScss;
};

export = ToolkitstylesModuleScssModule;
