/* tslint:disable */
// prettier-ignore
// ReSharper disable RedundantEmptyConstructor
// ReSharper disable InconsistentNaming
/*
 * This file is automatically generated by Visual Studio, all manual changes to this file will be lost.
 *
 * To regenerate this file make sure you
 *		1: Build the JSGenerator.CommandLine project
 *		2: Either run the project directly in Visual Studio, or execute HN.JsGenerator.CommandLine.exe in the folder <Repo>\SharePoint\Source\JsGenerator.CommandLine\bin\Debug
 *
 * This file is generated from classes implementing the IClientOperation interface in the Entities project or inherits from the ClientOperationResponse
 * class in the BusinessLogic project. All properties with the DataMember attribute in these or base classes is included.Properties which could not be properly
 * resolved defaults to TypeScripts 'any' type.
 *
 * Properties of IList, IEnumerable or ICollection(etc) is excluded(use a actual implementation to generate the type), some types are automatically
 * excluded since they should not be available in JavaScript(e.g.UserContext).
 */
// ------ Enum members ------
export enum AppointmentStatus
{
  ReservationUnconfirmed = 0,
  ReservationConfirmed = 1,
  ReservationDenied = 2,
  CancellationUnconfirmed = 3,
  CancellationConfirmed = 4,
  CancellationDenied = 5,
  ChangeUnconfirmed = 6,
  ChangeConfirmed = 7,
  ChangeDenied = 8,
  ChangeReplaced = 9,
  DidNotMeet = 10,
  ReservationConfirmedOtherDoctor = 11,
  Completed = 12,
  EnteredInError = 13
}
export enum AppointmentType {
  Online = 0,
  Offline = 1
}
export enum AvailableAppointmentsStatus {
  AppointmentsAvailable = 0,
  NoAppointmentsAvailable = 1,
  Rejected = 2,
  AccessDenied = 3,
  Error = 4,
  ServiceUnavailable = 5
}
export enum AvtaleKategori {
  Timeavtale = 0,
  Tidsvindu = 1
}
export enum AvtaleStatus {
  Ukjent = 0,
  ReservertUbekreftet = 1,
  ReservertBekreftet = 2,
  ReservertAvslatt = 3,
  AvbestiltUbekreftet = 4,
  AvbestiltBekreftet = 5,
  AvbestiltAvslatt = 6,
  EndretUbekreftet = 7,
  EndretBekreftet = 8,
  EndretAvslatt = 9,
  EndretErstattet = 10,
  IkkeMott = 11,
  ReservertBekreftetAnnenBehandler = 12,
  Gjennomfoert = 13,
  Feilregistrering = 14
}
export enum Berikingssamtykke {
  None = 0,
  TrengerIkkeSamtykke = 1,
  SamtykkeIkkeOppgitt = 2,
  IkkeSamtykket = 3,
  Samtykket = 4
}
export enum BrukType {
  AapnetDokument = 1
}
export enum CareLevel {
  Amb = 0,
  Ss = 1,
  Impd = 2,
  Imph = 3,
  Rtg = 4
}
export enum CertificateStatus {
  None = 0,
  Requested = 1,
  Created = 2,
  NotAvailable = 3,
  Attached = 4
}
export enum ChangeAppointmentSpecialistStatus {
  Booked = 0,
  Declined = 1,
  Error = 2
}
export enum ConsultationStatus {
  Unknown = 0,
  Ongoing = 1,
  Complete = 2
}
export enum ConversationCounterpartyType {
  Unknown = 0,
  GeneralPractitioner = 1,
  SpecialistHospital = 2,
  Helseregister = 3,
  Helfo = 4,
  Oppgave = 5,
  HelseNorge = 7,
  KommunaleHjemmebesok = 8,
  Forskningsprosjekt = 9,
  FormidlingOrganisasjon = 10,
  Primarhelsetjeneste = 11
}
export enum ConversationInitiatedBy {
  User = 0,
  Counterparty = 1
}
export enum ConversationItemType {
  Unknown = 0,
  GeneralPractitionerContact = 1,
  GeneralPractitionerConsultation = 2,
  GeneralPractitionerPrescription = 3,
  GeneralPractitionerAppointment = 4,
  SpecialistAppointmentLetter = 5,
  SpecialistQuestion = 6,
  SpecialistTimeChange = 7,
  SpecialistStopTreatment = 8,
  SpecialistConfirmAppointment = 9,
  Helseregister = 10,
  Coordinator = 11,
  BytteFastlege = 12,
  Oppgave = 13,
  DialogFullmakt = 14,
  NewSpecialistAppointmentLetter = 15,
  UpdatedSpecialistAppointmentLetter = 16,
  DeletedSpecialistAppointmentLetter = 17,
  RestoredSpecialistAppointmentLetter = 18,
  Meldingsformidling = 32,
  Direktevarsel = 33,
  Paminnelse = 34,
  HelsefagligKontakt = 35,
  Samtykkeforespørsel = 36,
  PrimarhelsetjenesteAppointment = 37,
  JournalAccess = 38
}
export enum ConversationStatus {
  Ongoing = 0,
  Completed = 1,
  Onetime = 2,
  NotStarted = 3
}
export enum ConversationType {
  Unknown = 0,
  GeneralPractitionerContact = 1,
  GeneralPractitionerConsultation = 2,
  GeneralPractitionerPrescription = 3,
  GeneralPractitionerAppointment = 4,
  SpecialistAppointmentLetter = 5,
  SpecialistQuestion = 6,
  SpecialistTimeChange = 7,
  SpecialistStopTreatment = 8,
  SpecialistConfirmAppointment = 9,
  SpecialistReferral = 11,
  SpecialistAppoinmentDialog = 12,
  Helseregister = 13,
  Coordinator = 14,
  BytteFastlege = 15,
  PasientreiserVedtak = 16,
  Oppgave = 17,
  DialogFullmakt = 20,
  NewSpecialistAppointmentLetter = 21,
  UpdatedSpecialistAppointmentLetter = 22,
  DeletedSpecialistAppointmentLetter = 23,
  RestoredSpecialistAppointmentLetter = 24,
  Meldingsformidling = 25,
  HelsefagligKontakt = 26,
  Samtykkeforespørsel = 27,
  PrimarhelsetjenesteAppointment = 28,
  JournalAccess = 29
}
export enum CoordinatorType {
  Unknown = 0,
  Cancer = 1
}
export enum CustodyType {
  None = 0,
  Delt = 1,
  Andre = 2,
  Mor = 3,
  Far = 4
}
export enum DeltMedRolle {
  Fastlege = 1
}
export enum DocumentHovedType {
  Arkivdokument = 1,
  Vedlegg = 2
}
export enum DokumentStatus {
  Ukjent = 0,
  Aktiv = 1,
  Erstattet = 2,
  Ugyldig = 3,
  Utkast = 4
}
export enum DokumentStatusType {
  Ukjent = 0,
  Aktiv = 1,
  Erstattet = 2,
  Ugyldig = 3
}
export enum DokumentType {
  Unknown = 0,
  Dokument = 1,
  Vedlegg = 2,
  Saksdokument = 3,
  SaksdokumentVedlegg = 4,
  Vedtak = 5,
  Besluttningsstotte = 6,
  Informasjonsskriv = 7,
  Registerinnsyn = 8,
  Registerinnsyn_KPR = 9
}
export enum DonorkortOperation {
  Create = 1,
  Delete = 2
}
export enum ExecuteCommandFor {
  None = 0,
  InnloggetBruker = 1,
  RepresentertBruker = 2
}
export enum ExternalAccessTokenRecipients {
  Personvern = 1,
  Felles = 2
}
export enum FinnesHelsedata {
  KanFinnes = 0,
  Finnes = 1
}
export enum FullmaktType {
  OrdinaerFullmakt = 3,
  BekreftetFullmakt = 4,
  UtenSamtykkekompenanseOver12 = 7
}
export enum GetFullmaktType {
  Ukjent = 0,
  Gitt = 1,
  Mottatt = 2,
  GittRepresentasjonsforhold = 3
}
export enum GetPersonForFullmaktStatus {
  Funnet = 1,
  IkkeFunnet = 2,
  ForMangeSok = 3,
  KanIkkeGiFullmaktTilDegSelv = 4,
  KanIkkeGiFullmaktForRepresentertBruker = 5,
  BrukerUnder18KanIkkeGiFullmakt = 6,
  BrukerUnder18KanIkkeHaFullmakt = 7,
  UgyldigPersonnummer = 8
}
export enum GjoremalStatus {
  Ny = 1,
  Utfort = 2,
  Utgatt = 3
}
export enum HealthRegion {
  Unknown = 0,
  HelseVest = 1,
  HelseNord = 2,
  HelseMidt = 3,
  HelseSorOst = 4
}
export enum HelsekontaktType {
  Helsepersonell = 1,
  Rolle = 2,
  Enhet = 3,
  Gruppe = 4
}
export enum HelseRegion {
  none = 0,
  hv = 1,
  hn = 2,
  hmn = 3,
  hso = 4
}
export enum HelseTjenesterType {
  Ukjent = 0,
  Helsetjenester = 1,
  Ordninger = 2,
  Helseopplysninger = 3
}
export enum HendelseType {
  Melding = 0,
  Paminnelse = 1,
  Direktevarsel = 2,
  Timeavtale = 3
}
export enum HttpStatusCode {
  Continue = 100,
  SwitchingProtocols = 101,
  OK = 200,
  Created = 201,
  Accepted = 202,
  NonAuthoritativeInformation = 203,
  NoContent = 204,
  ResetContent = 205,
  PartialContent = 206,
  MultipleChoices = 300,
  MovedPermanently = 301,
  Redirect = 302,
  SeeOther = 303,
  NotModified = 304,
  UseProxy = 305,
  Unused = 306,
  TemporaryRedirect = 307,
  BadRequest = 400,
  Unauthorized = 401,
  PaymentRequired = 402,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  NotAcceptable = 406,
  ProxyAuthenticationRequired = 407,
  RequestTimeout = 408,
  Conflict = 409,
  Gone = 410,
  LengthRequired = 411,
  PreconditionFailed = 412,
  RequestEntityTooLarge = 413,
  RequestUriTooLong = 414,
  UnsupportedMediaType = 415,
  RequestedRangeNotSatisfiable = 416,
  ExpectationFailed = 417,
  UpgradeRequired = 426,
  InternalServerError = 500,
  NotImplemented = 501,
  BadGateway = 502,
  ServiceUnavailable = 503,
  GatewayTimeout = 504,
  HttpVersionNotSupported = 505
}
export enum IdType {
  HerId = 0,
  HprId = 1,
  OrgId = 2,
  Other = 3,
  PersonalId = 4
}
export enum InnsynssperreType {
  Ingen = 0,
  Internet = 1,
  Full = 2,
  Delvis = 3
}
export enum KjernejournalReservationType {
  Reservert = 0,
  Slettet = 1
}
export enum KontaktAvType {
  Motpart = 1,
  Enhet = 2,
  Helsepersonell = 3,
  FunksjoneltMotpartPerson = 4,
  FunksjoneltMotpartOrg = 5
}
export enum KontaktKategori {
  Ukjent = 0,
  Helsepersonell = 1,
  Parorende = 2,
  Arbeidsgivere = 3
}
export enum KontaktPunktTjenesteType {
  KommunalHelseOgOmsorg = 1,
  Primaerhelsetjeneste = 2,
  Spesialisthelsetjenesten = 3
}
export enum KontaktType {
  Ukjent = 0,
  AnnenLege = 1,
  Helsepersonell = 2,
  AlternativBehandler = 3,
  NarmesteParorende = 4,
  Arbeidsgiver = 5,
  AndreParorende = 6
}
export enum LastMessageSentBy {
  User = 0,
  Counterparty = 1
}
export enum LegemiddelKilde {
  KJ = 0,
  RF = 1
}
export enum MerchandiseType {
  Other = 0,
  MedicalSupplies = 1,
  NutritionalSupplements = 2
}
export enum MessageSentStatus {
  Unknown = 0,
  Draft = 1,
  Sent = 2,
  ReceivedByJournal = 3,
  ReceivedByArchive = 4,
  RejectedByJournal = 5,
  Error = 6,
  Ghost = 99
}
export enum MessageType {
  Info = 0,
  Warning = 1,
  Error = 2
}
export enum MotpartType {
  Ukjent = 0,
  Fastlege = 1,
  SpesialistSykehus = 2,
  Helseregister = 3,
  Pasientreiser = 4,
  Helfo = 5,
  Oppgave = 6,
  Helsenorge = 7,
  KommunaleHjemmebesok = 8,
  Forskningsprosjekt = 9,
  FormidlingOrganisasjon = 10,
  Primarhelsetjeneste = 11
}
export enum NotificationLevel {
  Obligatorisk = 1,
  Viktig = 2,
  Mulig = 3
}
export enum OppforingsType {
  Ukjent = 0,
  SentraleHelseRegistre = 1,
  ForskningsprosjektHelseundersokelser = 2,
  NasjonaleKvalitetsRegistre = 3,
  BehandlingsrettedeRegistre = 4
}
export enum OppgaveStatus {
  Ny = 0,
  UnderArbeid = 1,
  Ferdig = 2
}
export enum OppgaveType {
  Ukjent = 0,
  Skjema = 1
}
export enum PatientStatus {
  LivingAbroad = 0,
  NotInRegularGPScheme = 1,
  NotAssignedDoctor = 2,
  PersonNumberTerminated = 3,
  PatientIsDead = 4,
  ReturnParentsDoctor = 5,
  DNumberWithoutDoctor = 6,
  SamiSpeaker = 7,
  NormalPatient = 8,
  UnknownPatient = 9,
  UnknownStatus = 10,
  VacantList = 11,
  LocumOnly = 12
}
export enum PrescriptionDeliveryMethod {
  DoctorsOffice = 0,
  Pharmacy = 1,
  HomeAddress = 2,
  SpecifiedAddress = 3
}
export enum PrescriptionState {
  Paper = 0,
  Active = 1,
  Completed = 2,
  Expired = 3,
  Terminated = 4,
  Renewed = 5,
  RenewedWithChange = 6,
  Inactive = 7,
  Dispatching = 8,
  PendingSLV = 9,
  Recalled = 10,
  SlvNotSet = 20,
  SlvConsideredAtPharmacy = 21,
  SlvPending = 22,
  SlvGranted = 23,
  SlvDenied = 24,
  NoStatus = 999
}
export enum PrescriptionStatus {
  Unknown = 0,
  NotRenewed = 1,
  Renewed = 2,
  PartiallyRenewed = 3
}
export enum PrescriptionType {
  Other = 0,
  Medicine = 1,
  MedicalSupplies = 2,
  NutritionalSupplements = 3
}
export enum ProfilePropertyCategoryType {
  None = 0,
  Notification = 1,
  Pilotdeltagelse = 2,
  Personvern = 3,
  Pasientjournal = 4
}
export enum ReferralType {
  NationalRefferal = 0,
  GeneralReferral = 1
}
export enum RegisterDialogType {
  Unknown = 0,
  RegisterInnsynOpplysninger = 1,
  RegisterInnsynUtlevering = 2,
  RegisterMeldeFeil = 3
}
export enum RejectedStatus {
  None = 0,
  Rejected = 1,
  AccessDenied = 2,
  GeneralError = 3,
  ServiceNotSupported = 4
}
export enum RepresentasjonforholdType {
  InnloggetBruker = 0,
  Fullmakt = 1,
  Foreldrerepresentasjon = 2,
  Saksbehandler = 3,
  SaksbehandlerFullmakt = 4
}
export enum ReservasjonStatusType {
  Reservert = 0,
  Trukket = 1
}
export enum ReservasjonType {
  None = 0,
  InnsynPasientjournal = 1,
  InnsynMinHelse = 4,
  KommunaltPasientOgBrukerregisterDirekteIdentifiserbare = 5,
  RepresentasjonAvBarn = 6,
  KommunaltPasientOgBrukerregisterGamle = 7,
  KommunaltPasientOgBrukerregisterAndreFormal = 8,
  Fastlegeordningen = 9
}
export enum RoleToPatientType {
  Ukjent = 0,
  BehandlingsansvarligLege = 3,
  Journalansvarlig = 4,
  Informasjonsansvarlig = 5,
  Fastlege = 6,
  FagligAnsvarligPsykiskHelsevern = 7,
  KoordinatorIndividuellPlan = 8,
  Primarkontakt = 9,
  UtskrivendeLege = 10,
  UtskrivendeSykepleier = 11,
  InstituerendeLege = 12,
  InnleggendeLege = 13,
  AnsvarligJordmor = 14,
  VikarForFastlege = 15,
  Turnuslege = 16,
  ForlopskoordinatorKreft = 17,
  KoordinatorSpesialisthelsetjenesteLoven = 18,
  Kontaktlege = 19,
  Kontaktpsykolog = 20,
  HelsefagligKontakt = 21,
  KontaktIPrimarhelseteam = 22,
  Tannhelsesekretaer = 101,
  Tannlege = 102,
  Tannpleier = 103,
  Tanntekniker = 104
}
export enum SamtykkeLevel {
  None = 0,
  Registerinnsyn = 1,
  Journalinnsyn = 2,
  Helsetjeneste = 3
}
export enum SamtykkeStatusType {
  Samtykket = 0,
  Trukket = 1,
  Utsatt = 2
}
export enum SamtykkeType {
  None = 0,
  Pha = 1,
  Bruksvilkar = 2,
  RefusjonPasientreiser = 3,
  UngdomsLosning = 4
}
export enum StatusKodeType {
  Reservert = 1,
  IkkeReservert = 2,
  Samtykket = 3,
  IkkeSamtykket = 4,
  TilgangsbegrensningOpprettet = 5,
  TilgangsbegrensningFjernet = 6,
  AnmodningTilbakeTrekkingSamtykke = 7
}
export enum SystemType {
  HelseNorge = 0,
  ESaks = 1
}
export enum TilgangsbegrensningDataType {
  Ingen = 1,
  Helsepersonell = 2,
  Organisasjon = 3
}
export enum TimeavtaleType {
  Specialist = 0,
  GeneralPractitioner = 1,
  Kommune = 2,
  NationalSpecialist = 3,
  Primarhelsetjeneste = 4
}
export enum TjenesteOmradeType {
  TimerOgForlop = 1,
  OkonomiOgRettigheter = 2,
  HelsehjelpOgHelseopplysninger = 3,
  InnsynJournalOgRegistre = 4,
  ProfilOgPersonvern = 5,
  Alle = 6,
  Vestlandspasienten = 7,
  InnsynIOpplysningerRegistrertOmMeg = 8,
  InnsynIPasientjournal = 9,
  DigitalHelsetjeneste = 10
}
export enum TjenesteStatusType {
  Deaktivert = 0,
  Aktivert = 1,
  MidlertidigDeaktivert = 2
}
export enum TjenesteTilgangStatus {
  None = 0,
  Ja = 1,
  Nei = 2,
  VetIkke = 3
}
export enum TokenScope {
  Full = 1,
  Restricted = 2
}
export enum TransportFormat {
  Amqp = 1,
  RestFhir = 2
}
export enum VarselmenyType {
  Paaminnelse = 1,
  Avtale = 2,
  Pasientreiser = 3,
  Melding = 4,
  Servicemelding = 5,
  Feilmelding = 6,
  Laeringsaktivitet = 7,
  Innsynsrapport = 8,
  Helsekontakt = 9,
  PasientreiserStegvisning = 10
}
export enum Visningstandard {
  Ingen = 0,
  Innsyn_v6_0_xsd = 1
}
export enum XDSDokumentKategori {
  EpikriserOgSammenfatninger = 1,
  Notater = 2,
  Korrespodanse = 3,
  Ukjent = 99
}
// ------ Constant members ------
export class TjenesteType {
  static TekniskTjeneste: number = -1;
  static IkkeInnloggetTjeneste: number = 0;
  static Timeavtaler: number = 1;
  static Fastlegetjenester: number = 6;
  static Legemidler: number = 7;
  static PersonligHelsearkiv: number = 8;
  static Fastlegevisning: number = 9;
  static InnsynPasientjournal: number = 10;
  static InnsynKjernejournal: number = 11;
  static Egenandeler: number = 12;
  static Profil: number = 13;
  static MinHelseForside: number = 15;
  static EksterneTjenester: number = 16;
  static Henvisninger: number = 17;
  static Pasientreiser: number = 18;
  static Forlopskoordinator: number = 19;
  static Meldinger: number = 20;
  static ByttFastlege: number = 21;
  static DialogForlop: number = 22;
  static DialogHelsehjelp: number = 23;
  static Fullmaktsadministrasjon: number = 24;
  static Helsekontakter: number = 25;
  static DialogOkonomi: number = 26;
  static Beslutningsstotte: number = 27;
  static DialogInnsyn: number = 28;
  static DialogPersonvern: number = 29;
  static Helseregistre: number = 30;
  static LoggOverBrukAvResepter: number = 31;
  static SykdomOgKritiskInformasjon: number = 32;
  static Forskning: number = 33;
  static MinHelse: number = 34;
  static Timeadministrasjon: number = 35;
  static Foreldresamtykke: number = 36;
  static DialogEgenHelseUngdom: number = 37;
  static KprTjenester: number = 38;
  static Vaksiner: number = 39;
  static LegemidlerLiB: number = 40;
  static InnsynRegisterinnhold: number = 41;
  static InnsynRegisterbruk: number = 42;
  static EKonsultasjon: number = 43;
  static Reseptfornyelse: number = 44;
  static EKontakt: number = 45;
  static Timebestilling: number = 46;
  static KritiskInfo: number = 47;
  static AapneKjernejournal: number = 48;
  static ProfildataOgKjernejournal: number = 49;
  static HelsekontakterIKjernejournal: number = 50;
  static LegemidlerFraKjernejournal: number = 51;
  static ProfildataOgKjernejournalReservasjon: number = 52;
  static PersonopplysningerFraKjernejournal: number = 53;
  static Donorkort: number = 54;
  static Samtykkeforesporsel: number = 55;
  static DialogForlopInformasjon: number = 56;
  static Pasientreiseradministrasjon: number = 57;
  static NyttHelsenorgeSamtykke: number = 58;
  static InngripendeForPersonvern: number = 59;
  static Skjemautfyller: number = 60;
  static SamvalgUtenLagring: number = 61;
  static MeldeFeilIBesokshistorikkKj: number = 62;
  static Verktoy: number = 63;
  static VerktoyUtforelse: number = 64;
  static InnsynRegisterinnholdReseptformidler: number = 65;
  static DialogSkjemaRegisterinnsyn: number = 66;
  static DialogSkjemaJournalinnsyn: number = 67;
  static DialogSkjemaHelsetjeneste: number = 68;
  static DialogSkjemaHelsetjenesteStreng: number = 69;
  static RegisterinnsynNasjonaleKvalitetsregister: number = 70;
  static ReiserMedRekvisisjon: number = 71;
}
export class FeatureNames {
  static ApiHelseNorge: string = "ApiHelseNorge";
  static ApneSkjemaFraStatiskLenke: string = "ApneSkjemaFraStatiskLenke";
  static BytteFastlege: string = "BytteFastlege";
  static BytteFastlegeAnonym: string = "BytteFastlegeAnonym";
  static BytteFastlegeFloNextRelease: string = "BytteFastlegeFloNextRelease";
  static BytteFastlegePrimaerhelseteam: string =
    "BytteFastlegePrimaerhelseteam";
  static DelingAvDokumenterNy: string = "DelingAvDokumenterNy";
  static DokumentTjenesteNy: string = "DokumentTjenesteNy";
  static Donorkort: string = "Donorkort";
  static FeilIBesoksHistorikkSaksBehandlerData: string =
    "FeilIBesoksHistorikkSaksBehandlerData";
  static FloReservasjon: string = "FloReservasjon";
  static ForhandsvisDokumenter: string = "ForhandsvisDokumenter";
  static ForskningDialog: string = "ForskningDialog";
  static ForskningInnsyn: string = "ForskningInnsyn";
  static FullSoknadPasientreiser: string = "FullSoknadPasientreiser";
  static HelsefagligKontakt: string = "HelsefagligKontakt";
  static HelsekontaktKontaktlege: string = "HelsekontaktKontaktlege";
  static HelseregistreDialog: string = "HelseregistreDialog";
  static HelseregistreInnsyn: string = "HelseregistreInnsyn";
  static HenvisningerHelseNord: string = "HenvisningerHelseNord";
  static HenvisningerHelseNordTimeSeksjon: string =
    "HenvisningerHelseNordTimeSeksjon";
  static HenvisningerHelseVest: string = "HenvisningerHelseVest";
  static InnsynOgTilgangslogg: string = "InnsynOgTilgangslogg";
  static JournalAccess: string = "JournalAccess";
  static KjNyKontaktperson: string = "KjNyKontaktperson";
  static KlagerPasientreiser: string = "KlagerPasientreiser";
  static KlientLogging: string = "KlientLogging";
  static Kvalitetsregistre: string = "Kvalitetsregistre";
  static KvalitetsregistreMedInnsyn: string = "KvalitetsregistreMedInnsyn";
  static KvalitetsregistreMedInnsynMottak: string =
    "KvalitetsregistreMedInnsynMottak";
  static KvalitetsregisterInnsynVedlegg: string =
    "KvalitetsregisterInnsynVedlegg";
  static KprReservasjon: string = "KprReservasjon";
  static Legemidler: string = "Legemidler";
  static LegemidlerIBruk: string = "LegemidlerIBruk";
  static MellomlagringSkjemaFraStatiskLenke: string =
    "MellomlagringSkjemaFraStatiskLenke";
  static MFRInnsyn: string = "MFRInnsyn";
  static MFRLoggOverBruk: string = "MFRLoggOverBruk";
  static NasjonaleHenvisningerHelseNord: string =
    "NasjonaleHenvisningerHelseNord";
  static NasjonaleTimeavtalerHelseNordHentDetaljer: string =
    "NasjonaleTimeavtalerHelseNordHentDetaljer";
  static NasjonaleHenvisningerHelseMidt: string =
    "NasjonaleHenvisningerHelseMidt";
  static NasjonaleTimeavtalerHelseMidtHentDetaljer: string =
    "NasjonaleTimeavtalerHelseMidtHentDetaljer";
  static NasjonaleHenvisningerHelseSorOst: string =
    "NasjonaleHenvisningerHelseSorOst";
  static NasjonaleTimeavtalerHelseSorOstHentDetaljer: string =
    "NasjonaleTimeavtalerHelseSorOstHentDetaljer";
  static NasjonaleHenvisningerHelseVest: string =
    "NasjonaleHenvisningerHelseVest";
  static NasjonaleTimeavtalerHelseVestHentDetaljer: string =
    "NasjonaleTimeavtalerHelseVestHentDetaljer";
  static NasjonaleTimeavtalerHelseNord: string =
    "NasjonaleTimeavtalerHelseNord";
  static NasjonaleTimeavtalerHelseMidt: string =
    "NasjonaleTimeavtalerHelseMidt";
  static NasjonaleTimeavtalerHelseSorOst: string =
    "NasjonaleTimeavtalerHelseSorOst";
  static NasjonaleTimeavtalerHelseVest: string =
    "NasjonaleTimeavtalerHelseVest";
  static NasjonaleTimeavtalerBatchUseJwtToken: string =
    "NasjonaleTimeavtalerBatchUseJwtToken";
  static OppgaveInnsendtMelding: string = "OppgaveInnsendtMelding";
  static PasientensLegemiddelliste: string = "PasientensLegemiddelliste";
  static PasientjournalTilgangsloggHelseNord: string =
    "PasientjournalTilgangsloggHelseNord";
  static PasientjournalTilgangsloggHelseSorOst: string =
    "PasientjournalTilgangsloggHelseSorOst";
  static PasientjournalTilgangsloggHelseVest: string =
    "PasientjournalTilgangsloggHelseVest";
  static PasientjournalXdsDokumenter: string = "PasientjournalXdsDokumenter";
  static PersonvelgerGetUnreadMessagesCount: string =
    "PersonvelgerGetUnreadMessagesCount";
  static RapporterMerknadPaFeilIBesokshistorikk: string =
    "RapporterMerknadPaFeilIBesokshistorikk";
  static ReseptformidlerInnsynV1: string = "ReseptformidlerInnsynV1";
  static RFInnsynInnhold: string = "RFInnsynInnhold";
  static SkjemaEksternRest: string = "SkjemaEksternRest";
  static SkjemautfyllerVedlegg: string = "SkjemautfyllerVedlegg";
  static SpesialistChangeAppointment: string = "SpesialistChangeAppointment";
  static SYSVAKInnsyn: string = "SYSVAKInnsyn";
  static SYSVAKLoggOverBruk: string = "SYSVAKLoggOverBruk";
  static TenfoldSendingAvVarsel: string = "TenfoldSendingAvVarsel";
  static TimeavtalerHelseNord: string = "TimeavtalerHelseNord";
  static TimeavtalerDialogHelseNord: string = "TimeavtalerDialogHelseNord";
  static TimeavtalerHelseVest: string = "TimeavtalerHelseVest";
  static VerticalUrl: string = "VerticalUrl";
  static VidereformidlingDpiPrint: string = "VidereformidlingDpiPrint";
  static VidereformidlingNy: string = "VidereformidlingNy";
  static ErPasientHelseNord: string = "ErPasientHelseNord";
  static SendMeldingerViaRabbit: string = "SendMeldingerViaRabbit";
  static BestillTimeViaFHIR: string = "BestillTimeViaFHIR";
  static BestilleNyPrimarhelsetjenesteTime: string =
    "BestilleNyPrimarhelsetjenesteTime";
  static SkjemaBackendValidering: string = "SkjemaBackendValidering";
  static SkrivMeldingSpesialistEnhet: string = "SkrivMeldingSpesialistEnhet";
  static VarslingNyttKontaktpunkt: string = "VarslingNyttKontaktpunkt";
  static SkjemautfyllerIkkeSensitivInformation: string =
    "SkjemautfyllerIkkeSensitivInformation";
  static FhirRevalidation: string = "FhirRevalidation";
}
export class HendelseLoggType {
  static TekniskTjeneste: number = -1;
  static BrukAvIkkeInnloggetTjeneste: number = 0;
  static LoggInn: number = 1;
  static BrukAvTjenesteAvtalevisning: number = 2;
  static BrukAvTjenesteVestlandspasienten: number = 5;
  static BrukAvTjenesteFastlegetjenester: number = 6;
  static BrukAvTjenesteReseptvisning: number = 7;
  static BrukAvTjenesteHelsearkiv: number = 8;
  static BrukAvTjenesteFastlegevisning: number = 9;
  static BrukAvTjenesteInnsynPasJour: number = 10;
  static BrukAvTjenesteInnsynKjernejournal: number = 11;
  static BrukAvTjenesteEgenandeler: number = 12;
  static BrukAvTjenesteProfil: number = 13;
  static BrukAvTjenesteFullmakt: number = 14;
  static MinHelseForside: number = 15;
  static BrukAvTjenesteHenvisninger: number = 16;
  static BrukAvTjenestePasientreiser: number = 17;
  static BrukAvTjenesteHelsekontakt: number = 18;
  static BrukAvTjenesteMeldingssenter: number = 19;
  static BrukAvTjenesteByttFastlege: number = 20;
  static BrukAvTjenesteFullmaktsadministrasjon: number = 21;
  static BrukAvBeslutningstotte: number = 22;
  static BrukAvHelseregistre: number = 23;
  static BrukAvTjenesteLoggOverBrukAvResepter: number = 24;
  static BrukAvTjenesteSykdomOgKritiskInfo: number = 25;
  static BrukAvTjenesteForskning: number = 26;
  static BrukAvTjenesteForlopskoordinator: number = 27;
  static BrukAvTjenesteTimeAdministrasjon: number = 28;
  static BrukAvTjenesteVaksiner: number = 29;
  static BrukAvTjenesteLegemidlervisning: number = 30;
  static EgendefinertLogging: number = 31;
  static EgendefinertLoggingHelseregistre: number = 32;
  static AapneKjernejournal: number = 33;
  static Donorkort: number = 34;
  static BrukAvTjenesteSkjemautfyller: number = 35;
  static BrukAvTjenesteVerktoy: number = 36;
  static BrukAvReiserMedRekvisisjon: number = 37;
}
// ------ Static members ------
export class PersonvernInnstillingDefinisjonIds {
  static Bruksvilkar: string = "7ac2178d-0e89-4251-9920-a496b2969640";
  static Pha: string = "2a132834-a9ff-4fa7-b104-7ff6c1218195";
  static Pasientreiser: string = "d39d21ad-8bf2-4fd3-b73b-02d21ee116db";
  static Ungdomslosning: string = "44eeaea9-b70a-4312-aa62-54e96a8aa802";
  static InnsynssperrePasientjournal: string =
    "d34a19d3-a474-4729-b097-dc4fe9515032";
  static InnsynssperreMinHelse: string = "49770acc-2e1b-4a8c-ac88-6bf9d18bfbce";
  static RepresentasjonAvBarn: string = "9d6dcf50-92da-468e-8d8c-0b59ff27904f";
  static KprDirekteIdentifiserbare: string =
    "d04a5c44-099d-4197-a322-2f9cb4b985b4";
  static KprAndreFormal: string = "d53cf0df-d029-4ef7-bde9-36acbd545bf0";
  static KprGamle: string = "2a5cc4d7-ab84-4449-b58a-5937a3f5dbd1";
  static Fastlegeordningen: string = "71ff6942-a738-4c43-8c9b-57d1ed4f785f";
  static PllAlleUnntattFastlegen: string =
    "fb922810-01f1-4b20-9999-bb25b47d1b44";
  static PllBestemtHelsepersonell: string =
    "07a49957-f6d8-4d2e-86e2-fe11997709e0";
  static InnsynIOpplysningerRegistrertOmMeg: string =
    "6ea1aa04-fad7-48c8-8432-1acb3fbf6d7b";
  static InnsynIPasientjournal: string = "dc5b5d14-deed-48e5-bf6d-99ed77f08a09";
  static DigitalHelsetjeneste: string = "fb640456-ae6f-4664-92c8-c6739d76caec";
}
// ReSharper restore RedundantEmptyConstructor
// ReSharper restore InconsistentNaming
/* tslint:enable */
