/* tslint:disable */
// prettier-ignore
// ReSharper disable RedundantEmptyConstructor
// ReSharper disable InconsistentNaming
/*
 * This file is automatically generated by Visual Studio, all manual changes to this file will be lost.
 *
 * To regenerate this file make sure you
 *		1: Build the JSGenerator.CommandLine project
 *		2: Either run the project directly in Visual Studio, or execute HN.JsGenerator.CommandLine.exe in the folder <Repo>\SharePoint\Source\JsGenerator.CommandLine\bin\Debug
 *
 * This file is generated from classes implementing the IClientOperation interface in the Entities project or inherits from the ClientOperationResponse
 * class in the BusinessLogic project. All properties with the DataMember attribute in these or base classes is included.Properties which could not be properly
 * resolved defaults to TypeScripts 'any' type.
 *
 * Properties of IList, IEnumerable or ICollection(etc) is excluded(use a actual implementation to generate the type), some types are automatically
 * excluded since they should not be available in JavaScript(e.g.UserContext).
 */
import {
    FinnesHelsedata,
    HttpStatusCode,
    OppforingsType,
} from './portalenums';
export type ISO8601 = string;
export class String {}
export class InfoMelding {
  Tittel: string;
  Body: string;
}
export class HelsePerson {
  Id: string;
  Fornavn: string;
  Etternavn: string;
  Alder: string;
  Kjonn: string;
}
export class TextMessage {
  Title: string;
  Body: string;
}
export class Vedlegg {
  DokumentId: string;
  DokumentNavn: string;
  DokumentHash: string;
}
export class BehandlingsvalgResult {
  JsonResult: string;
}
export class AvailableLanguages {
  Lcid: number;
  Language: string;
}
export class StottetRapport {}
export class Utekontor {
  Navn: string;
  Adresse: string;
  Postnummer: string;
  Poststed: string;
}
export class PageConfiguration {
  Title: string;
  Description: string;
  Url: string;
  HjelpeKontekstId: string;
  HjelpeGruppeId: string;
  Tjeneste: number;
  Tjenestemeny: string;
  TjenestemenyNavn: string;
  VertikalAssetsPath: string;
  NavigateBackLinkTitle: string;
  NavigateBackLinkURL: string;
  MetaDescription: string;
  DoNotRedirectToHomeWhenChangingRepresentation: boolean;
  HendelseLoggType: string;
}
export class VentetidTabell {
  Overskrifter: Array<String>;
  Rader: any;
  HarFlapper: boolean;
  HarVolumTall: boolean;
}
export class Link {
  Title: string;
  Href: string;
  Class: string;
}
export class Innsyn {
  InnsynObjects: Array<InnsynObject>;
  Vedlegg: Array<Vedlegg>;
  StottedeRapporter: Array<StottetRapport>;
}
export class Register {
  RegisterId: string;
  Navn: string;
  Forkortelse: string;
  BeskrivelseFormaal: string;
  BeskrivelseOppfoering: string;
  Databehandlingsansvarlig: string;
  InformasjonLenkeTekst: string;
  InformasjonLenke: string;
  InnsynsrettLenkeTekst: string;
  InnsynsrettLenke: string;
  Sekvensnummer: number;
  RettsligGrunnlag: string;
  SekvensnrInnenforParagraf: number;
  HasDialog: boolean;
  DialogSubTjeneste: number;
  HerId: number;
  Innsynslenke: string;
  OppforingsType: OppforingsType;
  FinnesHelsedata: FinnesHelsedata;
  OrganisasjonsNummer: number;
  SistOppdatert: ISO8601;
  SistOppdatertString: string;
}
export class Skjema {
  Id: string;
  ContentType: string;
  Content: string;
  QuestionnairePath: string;
}
export class Behandling {
  Id: string;
  Navn: string;
  Gruppe: string;
  InfoMelding: InfoMelding;
  VentetidTabell: VentetidTabell;
  Avdeling: string;
  IsException: boolean;
}
export abstract class XObject {}
export class FeilKildeListe {
  LegensSpesialiteter: TextMessage;
  Utekontor: TextMessage;
  Gruppepraksis: TextMessage;
  Fellesliste: TextMessage;
  PrimarHelseTeam: TextMessage;
}
export class ResponseBase {
  FloResponse: number;
  HnResponse: number;
}
export class CompositeCode {
  ChangedDate: ISO8601;
  CodeText: string;
  CodeValue: string;
  Codes: any;
  Comment: string;
  CompositeCodeGroupLanguage: string;
  CompositeCodeGroupName: string;
  CompositeCodeGroupOID: number;
  CompositeCodeGroupVersion: number;
  ReplacedCodes: any;
  ReplacingCodes: any;
}
export class Tile {
  Title: string;
  Description: string;
  Link: string;
  TjenesteType: number;
  Banner: string;
  Columns: number;
  Image: string;
  Internal: boolean;
  RequiresLogin: boolean;
  ShowUnreadMessageCount: boolean;
  NeedsConfirmation: boolean;
  WelcomeTile: boolean;
  Children: any;
}
export class InnsynObject {
  Title: string;
  Type: string;
  Content: string;
  Attributes: any;
  Children: Array<InnsynObject>;
}
export class HelsePersonSamisk extends HelsePerson {
  Samisk: boolean;
}
export class PrimarHelsePerson extends HelsePerson {
  Rolle: string;
}
export class PortalInitialData extends ResponseBase {
  Fylker: any;
}
export class AvtaleDetaljer extends ResponseBase {
  LegensSpesialiteter: Array<String>;
  Utekontor: Array<Utekontor>;
  Gruppepraksis: Array<HelsePersonSamisk>;
  Fellesliste: Array<HelsePersonSamisk>;
  PrimarHelseTeam: Array<PrimarHelsePerson>;
  FeilKildeListe: FeilKildeListe;
}
export class AvtaleSok extends ResponseBase {
  Resultater: any;
}
export abstract class XNode extends XObject {}
export class VikarFastlege extends HelsePerson {
  TilDato: ISO8601;
  FraDato: ISO8601;
  Prosentandel: number;
  VikarFor: string;
}
export class Fastlege extends HelsePersonSamisk {
  HprNummer: number;
  Stillingsprosent: string;
  Autorisert: string;
}
export abstract class XContainer extends XNode {}
export class XElement extends XContainer {}
export abstract class OperationResponse extends Response {
  StatusCode: HttpStatusCode;
  InformationMessage: TextMessage;
  WarningMessage: TextMessage;
  ErrorMessage: TextMessage;
  RedirectUrl: string;
}
export class ClientOperationResponse extends OperationResponse {}
export class ClientErrorOperationResponse extends OperationResponse {}
export class ClientStreamOperationResponse extends ClientOperationResponse {}
export class HentBehandlingsvalgOperationResponse extends ClientOperationResponse {
  Resultater: BehandlingsvalgResult;
}
export class GetAvailableLanguagesOperationResponse extends ClientOperationResponse {
  AvailableLanguages: Array<AvailableLanguages>;
}
export class GetInitialDataOperationResponse extends ClientOperationResponse {
  InitialData: PortalInitialData;
}
export class GetAvtaleDetaljerOperationResponse extends ClientOperationResponse {
  AvtaleDetaljer: AvtaleDetaljer;
}
export class AvtaleSokOperationResponse extends ClientOperationResponse {
  Resultater: AvtaleSok;
}
export class ClientXmlOperationResponse extends ClientOperationResponse {
  Content: XElement;
}
export class GetFeatureTogglesOperationResult extends ClientOperationResponse {
  FeatureToggles: any;
}
export class GetPageConfigurationsOperationResponse extends ClientOperationResponse {
  Pages: Array<PageConfiguration>;
}
export class GetFooterOperationResult extends ClientOperationResponse {
  About: Array<Link>;
  Social: Array<Link>;
  Networks: Array<Link>;
}
export class GetEnvironmentOperationResponse extends ClientOperationResponse {
  Level: number;
}
export class GetResxOperationResult extends ClientOperationResponse {
  Resources: string;
}
export class GetTilesOperationResult extends ClientOperationResponse {
  Helsetjenester: Array<Tile>;
  Innsynstjenester: Array<Tile>;
  EksterneTjenester: Array<Tile>;
}
export class UploadTestRegisterInnsynXmlOperationResponse extends ClientOperationResponse {
  Innsyn: Innsyn;
}
export class GetRegisteroppforingPortalOperationResponse extends ClientOperationResponse {
  Registre: Array<Register>;
}
export class GetSkjemaFraKatalogOperationResponse extends ClientOperationResponse {
  FormDefinition: Skjema;
  OpprettetFraLenke: boolean;
}
export class GetFeatureToggleOperationResult extends ClientOperationResponse {
  IsEnabled: boolean;
}
export class GetBehandlingsstederVentetidOperationResponse extends ClientOperationResponse {
  Behandling: Behandling;
}
export abstract class PortalCommand {}
export class GetTilesPortalCommand extends PortalCommand {}
export class GetResxPortalCommand extends PortalCommand {
  Culture?: string;
  Name?: string;
}
export class GetEnvironmentCommand extends PortalCommand {}
export class GetFooterPortalCommand extends PortalCommand {}
export class GetPageConfigurationsCommand extends PortalCommand {}
export class LogPortalCommand extends PortalCommand {
  Level?: number;
  Message?: string;
  Url?: string;
  UserAgent?: string;
}
export class UploadTestRegisterInnsynXmlCommand extends PortalCommand {
  Xml?: string;
}
export class GetFeatureToggleCommand extends PortalCommand {
  FeatureName?: string;
}
export class AvtaleSokPortalCommand extends PortalCommand {
  Kommuner?: Array<String>;
  Bydeler?: Array<String>;
  LegekontorNavn?: string;
  LegeNavn?: string;
}
export class GetAvtaleDetaljerPortalCommand extends PortalCommand {
  HprNummer?: number;
  AvtaleId?: number;
  KontorId?: number;
  Fellesliste?: boolean;
  Gruppepraksis?: boolean;
  PrimarHelseTeamId?: number;
}
export class GetGruppeFellesListerPortalCommand extends PortalCommand {
  KontorId?: number;
  Fellesliste?: boolean;
  Gruppepraksis?: boolean;
}
export class GetInitialDataPortalCommand extends PortalCommand {
  InvalidateCache?: boolean;
}
export class GetAvailableLanguagesCommand extends PortalCommand {
  Behandlingsvalg?: string;
}
export class HentBehandlingsvalgCommand extends PortalCommand {
  Behandlingsvalg?: string;
  Publisert?: boolean;
  ContentType?: number;
  LcidLanguage?: number;
}
export class GetFeatureTogglesCommand extends PortalCommand {
  Features?: any;
}
export class CreateBsvDataContentCommand extends PortalCommand {
  ContentTypeId?: number;
  ContentValue?: string;
  Tittel?: string;
  BehandlingsvalgKode?: string;
  Publiser?: boolean;
  LcidLanguage?: number;
}
export class SetLanguageCommand extends PortalCommand {
  Language?: string;
}
export class GetSkjemaFraKatalogCommand extends PortalCommand {
  Query?: string;
  ContentType?: string;
}
export class GetBehandlingerCommand extends PortalCommand {}
export class GetBehandlingsstedCommand extends PortalCommand {
  OrganizationNumber?: string;
}
export class GetBehandlingsstedDataCommand extends PortalCommand {
  BehandlingsId?: string;
  OrganisasjonsId?: string;
  OvOrganisasjonsId?: string;
}
export class GetBehandlingsstederCommand extends PortalCommand {}
export class GetBehandlingsstederMedBehandlingCommand extends PortalCommand {
  BehandlingsId?: string;
}
export class GetBehandlingsstederVentetidCommand extends PortalCommand {
  BehandlingId?: string;
}
export class GetRegisteroppforingPortalCommand extends PortalCommand {
  InvalidateCache?: boolean;
  OppforingsTyper?: Array<OppforingsType>;
}
export class GetBusinessCommand extends PortalCommand {
  OrgNr?: number;
  Domain?: CompositeCode;
}
export class GetBusinessesHavingServiceOfTypeCommand extends PortalCommand {
  ServiceType?: CompositeCode;
  Domain?: CompositeCode;
}
export class GetOversiktOverBehandlingsstederCommand extends PortalCommand {}
export class GetPrivateBehandlingsstederCommand extends PortalCommand {}
export class GetRHFsCommand extends PortalCommand {}
export class GetTreatmentGroupingsCommand extends PortalCommand {
  Domain?: CompositeCode;
}
export class GetTreatmentsInDomainCommand extends PortalCommand {
  Domain?: CompositeCode;
}
export class GetBusinessesHavingServiceInDomainCommand extends PortalCommand {
  Domain?: CompositeCode;
}
export class GetPortalRoutesCommand extends PortalCommand {}
// ReSharper restore RedundantEmptyConstructor
// ReSharper restore InconsistentNaming
/* tslint:enable */
