/* tslint:disable */
// prettier-ignore
// ReSharper disable RedundantEmptyConstructor
// ReSharper disable InconsistentNaming
/*
 * This file is automatically generated by Visual Studio, all manual changes to this file will be lost.
 *
 * To regenerate this file make sure you
 *		1: Build the JSGenerator.CommandLine project
 *		2: Either run the project directly in Visual Studio, or execute HN.JsGenerator.CommandLine.exe in the folder <Repo>\SharePoint\Source\JsGenerator.CommandLine\bin\Debug
 *
 * This file is generated from classes implementing the IClientOperation interface in the Entities project or inherits from the ClientOperationResponse
 * class in the BusinessLogic project. All properties with the DataMember attribute in these or base classes is included.Properties which could not be properly
 * resolved defaults to TypeScripts 'any' type.
 *
 * Properties of IList, IEnumerable or ICollection(etc) is excluded(use a actual implementation to generate the type), some types are automatically
 * excluded since they should not be available in JavaScript(e.g.UserContext).
 */
// ------ Enum members ------
export enum FinnesHelsedata
{
  KanFinnes = 0,
  Finnes = 1
}
export enum HttpStatusCode {
  Continue = 100,
  SwitchingProtocols = 101,
  OK = 200,
  Created = 201,
  Accepted = 202,
  NonAuthoritativeInformation = 203,
  NoContent = 204,
  ResetContent = 205,
  PartialContent = 206,
  MultipleChoices = 300,
  MovedPermanently = 301,
  Redirect = 302,
  SeeOther = 303,
  NotModified = 304,
  UseProxy = 305,
  Unused = 306,
  TemporaryRedirect = 307,
  BadRequest = 400,
  Unauthorized = 401,
  PaymentRequired = 402,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  NotAcceptable = 406,
  ProxyAuthenticationRequired = 407,
  RequestTimeout = 408,
  Conflict = 409,
  Gone = 410,
  LengthRequired = 411,
  PreconditionFailed = 412,
  RequestEntityTooLarge = 413,
  RequestUriTooLong = 414,
  UnsupportedMediaType = 415,
  RequestedRangeNotSatisfiable = 416,
  ExpectationFailed = 417,
  UpgradeRequired = 426,
  InternalServerError = 500,
  NotImplemented = 501,
  BadGateway = 502,
  ServiceUnavailable = 503,
  GatewayTimeout = 504,
  HttpVersionNotSupported = 505
}
export enum OppforingsType {
  Ukjent = 0,
  SentraleHelseRegistre = 1,
  ForskningsprosjektHelseundersokelser = 2,
  NasjonaleKvalitetsRegistre = 3,
  BehandlingsrettedeRegistre = 4
}
// ReSharper restore RedundantEmptyConstructor
// ReSharper restore InconsistentNaming
/* tslint:enable */
