// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    'safetextarea__char-counter': string;
    'safetextarea__char-counter__hidden-text': string;
    'safetextarea__char-counter__length': string;
    'safetextarea__char-counter__length--invalid': string;
    'safetextarea__printable-textarea-content': string;
    safetextarea__textarea: string;
    'safetextarea__textarea--large': string;
    'safetextarea__textarea--medium': string;
    'safetextarea__textarea--small': string;
    'safetextarea__textarea--state_validationerror': string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesModuleScssNamespace.IStylesModuleScss;
};

export = StylesModuleScssModule;
