/* tslint:disable */
/*
 * This file is automatically generated by SOT
 *
 * This file is for typings support only, it will not supply the actual text, you will still need to download the correct culture spesific .resx file.
 */
export type HNCoreFrontendMicrowebHeaderFooter = {
  /**
   * meny
   */
  headerButtonMeny: string;
  /**
   * søk
   */
  headerButtonSok: string;
  /**
   * Logg inn
   */
  headerButtonLogin: string;
  /**
   * Logg ut
   */
  headerButtonLogout: string;
  /**
   * Dette har skjedd siden sist
   */
  headerMenuProfileVarslingerTitle: string;
  /**
   * Hvem vil du bruke Helsenorge på vegne av?
   */
  headerMenuProfileRepresentasjonerTitle: string;
  /**
   * Profil og innstillinger
   */
  headerMenuProfileLinksTitle: string;
  /**
   * Du var sist innlogget :
   */
  headerMenuProfileSistInnlogget: string;
  /**
   * deg selv
   */
  headerMenuProfileRepresentasjonerDegSelv: string;
  /**
   * du har fullmakt
   */
  headerMenuProfileRepresentasjonerDuHarFullmakt: string;
  /**
   * du har foreldreansvar
   */
  headerMenuProfileRepresentasjonerDuHarForeldreansvar: string;
  /**
   * Du har
   */
  headerMenuProfileVarslingerDuHar: string;
  /**
   * nye meldinger
   */
  headerMenuProfileVarslingerMeldinger: string;
  /**
   * nye hendelser
   */
  headerMenuProfileVarslingerHendelser: string;
  /**
   * Hva leter du etter?
   */
  headerMenuSearchTitle: string;
  /**
   * Søk
   */
  headerMenuSearchInput: string;
  /**
   * Søk
   */
  headerMenuSearchSubmit: string;
  /**
   * /kontaktinformasjon-og-varseloppsett
   */
  headerMenuProfileLinksKontaktinformasjonOgVarseloppsettUrl: string;
  /**
   * Kontaktinformasjon og varseloppsett
   */
  headerMenuProfileLinksKontaktinformasjonOgVarseloppsettTitle: string;
  /**
   * /personopplysninger
   */
  headerMenuProfileLinksPersonopplysningerUrl: string;
  /**
   * Personopplysninger
   */
  headerMenuProfileLinksPersonopplysningerTitle: string;
  /**
   * Bruk av helsetjenester og ordninger
   */
  headerMenuProfileLinksBrukAvHelsetjenesterTitle: string;
  /**
   * /Bruk-av-helsetjenester-og-ordninger
   */
  headerMenuProfileLinksBrukAvHelsetjenesterUrl: string;
  /**
   * /fullmakter
   */
  headerMenuProfileLinksFullmakterUrl: string;
  /**
   * Fullmakter
   */
  headerMenuProfileLinksFullmakterTitle: string;
  /**
   * Logg over bruk
   */
  headerMenuProfileLinksLoggOverBrukTitle: string;
  /**
   * /logg-over-bruk-av-tjenester
   */
  headerMenuProfileLinksLoggOverBrukUrl: string;
  /**
   * /auth/signin
   */
  headerButtonLoginUrl: string;
  /**
   * /auth/signout
   */
  headerButtonLogoutUrl: string;
  /**
   * ingen
   */
  headerMenuProfileVarslingerIngen: string;
  /**
   * Innhold A-Å
   */
  headerMenuBasicInnholdAAATitle: string;
  /**
   * https://helsenorge.no/en
   */
  headerMenuBasicInnholdAAAUrl: string;
  /**
   * Engelsk
   */
  headerMenuBasicEngelskTitle: string;
  /**
   * https://helsenorge.no/en/
   */
  headerMenuBasicEngelskUrl: string;
};

export type HNCoreFrontendNPMPackagesCMS = {
  /**
   * Søk
   */
  searchSubmitLabel: string;
  /**
   * Feil. Vi klarer ikke å hente søkeforslag. Vennligst prøv igjen senere.
   */
  searchErrorSuggestionFetch: string;
  /**
   * Søk
   */
  searchPlaceholder: string;
};

export type HNCoreFrontendWebForside = {
  /**
   * Søk i kvalitetssikret helseinformasjon
   */
  searchContainerTitle: string;
  /**
   * Hva leter du etter?
   */
  searchContainerPlaceholder: string;
  /**
   * Gå til Innhold A til Å
   */
  searchContainerAnchor: string;
};

/* tslint:enable */
