// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    datepicker: string;
    'datepicker--haserror': string;
    'datepicker__arrow-icon': string;
    'datepicker__header-navigation': string;
    'datepicker__header-navigation--disabled': string;
    'datepicker__input-icon': string;
    datepicker__legend: string;
    datepicker__legend__label: string;
    'datepicker__legend__label--hidden': string;
    datepicker__legend__sublabel: string;
    'datepicker__month-selector': string;
    'datepicker__month-year-selector': string;
    'datepicker__native-input': string;
    'datepicker__native-input--fullwidth': string;
    'datepicker__year-selector': string;
    'datepicker__year-view': string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesModuleScssNamespace.IStylesModuleScss;
};

export = StylesModuleScssModule;
