// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ThemeModuleScssNamespace {
  export interface IThemeModuleScss {
    container: string;
    containerOpen: string;
    input: string;
    suggestion: string;
    suggestionHighlighted: string;
    suggestionsContainer: string;
    suggestionsList: string;
  }
}

declare const ThemeModuleScssModule: ThemeModuleScssNamespace.IThemeModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ThemeModuleScssNamespace.IThemeModuleScss;
};

export = ThemeModuleScssModule;
