// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    mol_yearmonthinput__fieldwrapper: string;
    mol_yearmonthinput__yearfield: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesModuleScssNamespace.IStylesModuleScss;
};

export = StylesModuleScssModule;
